### ISSUE TITLE
Guard is awesome

### ISSUE THREAD

**Issue by umireon** [nimiusrd/MyFirstRepository#4]
https://github.com/guard/guard

**Comment by nimiusrd** [comment]
hihiihihi

2015-07-03 23:07 GMT+09:00 Kaito Udagawa notifications@github.com:

> —
> Reply to this email directly or view it on GitHub
> https://github.com/nimiusrd/MyFirstRepository/issues/4.

## 

-+=+-+=+-+=+-+=+-+=+-+=+-+=+-+=+-
宇田川 <nimius.rd+basket@gmail.com>

**Comment by umireon** [comment]
could u close this issue?

**Comment by nimiusrd** [comment]
colose this
